version: '3.8'

services:
  zookeeper:
    image: venicedb/apache-zookeeper:3.9.0
    container_name: zookeeper
    hostname: zookeeper
    healthcheck:
        test: ["CMD-SHELL", "echo ruok | nc zookeeper 2181"]
        start_period: 10s
        interval: 5s
        timeout: 5s
        retries: 5

  kafka:
   image: docker.redpanda.com/vectorized/redpanda:v21.11.15
   container_name: kafka
   command:
   - redpanda
   - start
   - --smp
   - '1'
   - --reserve-memory
   - 0M
   - --overprovisioned
   - --node-id
   - '0'
   - --kafka-addr
   - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
   - --advertise-kafka-addr
   - PLAINTEXT://kafka:29092,OUTSIDE://kafka:9092
   - --pandaproxy-addr
   - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
   - --advertise-pandaproxy-addr
   - PLAINTEXT://kafka:28082,OUTSIDE://kafka:8082
   ports:
   - 8081:8081
   - 8082:8082
   - 9092:9092
   - 28082:28082
   - 29092:29092


  venice-controller:
    image: venicedb/venice-controller:0.4.17
    container_name: venice-controller
    hostname: venice-controller
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
        test: ["CMD-SHELL", "sleep 5"]
        start_period: 20s
        interval: 5s
        timeout: 20s
        retries: 5

  venice-server:
    image: venicedb/venice-server:0.4.17
    container_name: venice-server
    hostname: venice-server
    depends_on:
      venice-controller:
        condition: service_healthy
    healthcheck:
        test: ["CMD-SHELL", "sleep 5"]
        start_period: 20s
        interval: 5s
        timeout: 20s
        retries: 5

  venice-router:
    image: venicedb/venice-router:0.4.17
    container_name: venice-router
    hostname: venice-router
    depends_on:
      venice-server:
        condition: service_healthy
    healthcheck:
        test: ["CMD-SHELL", "sleep 5"]
        start_period: 20s
        interval: 5s
        timeout: 20s
        retries: 5

  venice-client:
    image: venicedb/venice-client:0.4.17
    container_name: venice-client
    hostname: venice-client
    tty: true
    depends_on:
      venice-router:
        condition: service_healthy
