# GitHub Actions workflow for running static analysis and unit tests
name: AnalyseStatiqueEtTestsUnitaires

on: [push, pull_request, workflow_dispatch]

jobs:
  ValidateGradleWrapper:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
     group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
     cancel-in-progress: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

  Internal:
   uses: ./.github/workflows/UnitTests-core.yml
   with:
    artifact_suffix: internal
    arg: :clients:da-vinci-client:jacocoTestCoverageVerification :clients:da-vinci-client:diffCoverage --continue


  StaticAnalysisAndUnitTestsCompletionCheck:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    needs: [Internal]
    timeout-minutes: 120
    if: success() || failure()  # Always run this job, regardless of previous job status
    steps:
      - name: Check previous job statuses
        run: |
         if [ "${{ needs.Internal.result }}" != "success" ]; then
           echo "Internal module unit tests failed."
           exit 1
         fi
      # If all previous jobs were successful, proceed
      - name: Final Completion Check
        run: echo "All checks passed successfully!"



